# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.

# Site settings
title: "Sobigdata Master"
subtitle: "Master in Big Data Analytics & AI for Society"
email: masterbigdata@unipi.it
description: >-
  Il Master in Big Data Analytics and Artificial Intelligence for Society dell'Università di Pisa è un percorso annuale per diventare data scientist


# Navigazione
navbar:
  style: dual
  brand:
    title: "Sobigdata Master"
    img: "./assets/images/Logo_masthead.png"
    url: /
  nav:
    - title: Iscrizione
      url: /iscrizione
    - title: Didattica
      url: /didattica
    - title: Partner
      url: /partner
    - title: Progetti
      url: /progetti
    - title: Docenti
      child:
        - title: Corpo Docente
          url: /docenti
        - title: Direttivo
          url: /direttivo
    - title: Studenti
      url: /studenti
    - title: Contatti
      url: /contatti

# Personalizzazione Aspetto
googlefonts:
  - url: "https://fonts.googleapis.com/css2?family=Rajdhani:wght@300;400;500;600;700&display=swap"
  - url: "https://fonts.googleapis.com/css2?family=Space+Mono:ital,wght@0,400;0,700;1,400;1,700&display=swap"
  - url: "https://fonts.googleapis.com/css2?family=Lekton:ital,wght@0,400;0,700;1,400&display=swap"

chulapa-skin:
  skin: "graymor"
  vars:
    body-color: "#07286E"
    body-bg: "#fff"
    footer-chulapa-bg-color: "#07286E"
    footer-chulapa-text-color: "#fff"
    navbar-chulapa-bg-color: "#07286E"
    navbar-chulapa-text-color: "#fff"
    primary: "#07286E"
    link-color: "#9b1626"
    link-hover-color: "#de1f36"
    link-decoration: "underline"
    headings-font-family: "Rajdhani"

##################################################
#    Configurazioni di sistema (NON modificare)
##################################################

theme: chulapa-jekyll
plugins:
  - jekyll-feed

collections:
  pages:
    output: true
    permalink: /:path

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: https://www.linkedin.com/company/sobigdata
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: https://www.twitter.com/sobigdata
    - label: "Facebook"
      icon: "fab fa-facebook"
      url: https://www.facebook.com/sobigdata
  copyright: "2026 – SoBigData Master"

sass:
  quiet_deps: true

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .idea/

livereload: true
baseurl: "" 
url: "" 
future: true