# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.

# Site settings
title: "Sobigdata Master"
subtitle: "Master in Big Data Analytics & AI for Society"
email: your-email@example.com
description: >-
  Il Master in Big Data Analytics and Artificial Intelligence for Society dell'Università di Pisa è un percorso annuale per diventare data scientist

# Info Repository (Aggiorna questi link con quelli del tuo progetto)
github_repo:
  - name: "Group 0 - Project repository"
    url: "https://github.com/sobigdata-master/progettone-template"
  - name: "Group 0 - Website repository"
    url: "https://github.com/sobigdata-master/progettone-template"

# Navigazione
navbar:
  style: dual
  brand:
    title: "Sobigdata Master"
    img: "./assets/images/Logo_masthead.png"
    url: /
  nav:
    - title: Iscrizione
      url: /iscrizione
    - title: Didattica
      child:
        - title: 2025-2026
          url: /didattica/25-26
        - title: 2024-2025
          url: /didattica/24-25
        - title: 2023-2024
          url: /didattica/23-24
        - title: 2022-2023
          url: /didattica/22-23
        - title: 2021-2022
          url: /didattica/21-22
        - title: 2020-2021
          url: /didattica/20-21
        - title: 2019-2020
          url: /didattica/19-20
        - title: 2018-2019
          url: /didattica/18-19
        - title: 2017-2018
          url: /didattica/17-18
        - title: 2016-2017
          url: /didattica/16-17
        - title: 2015-2016
          url: /didattica/15-16
    - title: Partner
      url: /partner
    - title: Progetti
      url: /progetti
    - title: Persone
      child:
        - title: Corpo Docente
          url: /docenti
        - title: Direttivo
          url: /direttivo
        - title: Studenti
          url: /studenti
    - title: Contatti
      url: /contatti

# Personalizzazione Aspetto
googlefonts:
  - url: "https://fonts.googleapis.com/css2?family=Rajdhani:wght@300;400;500;600;700&display=swap"
  - url: "https://fonts.googleapis.com/css2?family=Space+Mono:ital,wght@0,400;0,700;1,400;1,700&display=swap"
  - url: "https://fonts.googleapis.com/css2?family=Lekton:ital,wght@0,400;0,700;1,400&display=swap"

chulapa-skin:
  skin: "graymor"
  vars:
    body-color: "#07286E"
    body-bg: "#fff"
    footer-chulapa-bg-color: "#07286E"
    footer-chulapa-text-color: "#fff"
    navbar-chulapa-bg-color: "#07286E"
    navbar-chulapa-text-color: "#fff"
    primary: "#07286E"
    link-color: "#9b1626"
    link-hover-color: "#de1f36"
    link-decoration: "underline"
    headings-font-family: "Rajdhani"

##################################################
#    Configurazioni di sistema (NON modificare)
##################################################

theme: chulapa-jekyll
plugins:
  - jekyll-feed

collections:
  pages:
    output: true
    permalink: /:path

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: https://www.linkedin.com/company/sobigdata
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: https://www.twitter.com/sobigdata
    - label: "Facebook"
      icon: "fab fa-facebook"
      url: https://www.facebook.com/sobigdata
  copyright: "2026 – SoBigData Master"

sass:
  quiet_deps: true

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .idea/

livereload: true
baseurl: "" 
url: "" 
future: true